try {
    console.log(p);
} catch (e) {
    console.error(e.error);
}